name: ReitzMMO
version: 1.11
author: Paully104
main: com.paully104.reitzmmo.Main
api-version: 1.14
commands:
        reitz:
                     description: Main ReitzRPGMMO command listings
                     usage: /reitz
        rrm:
                     description: Main ReitzRPGMMO command listings
                     usage: /rrm
        rparty:
                    description: Party system for ReitzRPGMMO
                    usage: /rparty

